### ISSUE TITLE
TODO: Make mechanical machine models not generate nearly as many models as it currently does

### ISSUE THREAD

**Issue by BeetoGuy** [BeetoGuy/BetterWithMods#102]
Currently, the mechanical machines block, with all current states, generates 3,456 block models. This is incredibly inefficient. The most manageable solution I can think of for this problem is to remove the tilting and subtype states, moving the crucible and cauldron to a separate block without an on/off state but with a tilting state, and making the subtypes bound to TESRs. This will decrease the model load from 3,456 models in one block to 58-60 in two blocks, assuming my math is right. I don't know about you guys, but that seems like a hell of a difference to me.
TODO list: 
- [ ] Make a crucible/cauldron block with a tilting state (with EnumFacing.DOWN predicated out, preferably).
- [ ] For legacy purposes, keep the crucible/cauldron in the main mech machines block, but without tilting. The tile entity will need cases for this, and maybe a conversion recipe from old to new.
- [x] TileEntitySpecialRenders for turntable buttons and filtered hopper filters.

**Comment by BeetoGuy** [comment]
Actually, now that I think about it, if we let slot fill be handled by a TESR, we can not only make visible inventories look more visually appealing by slightly raising fill level for each occupied slot, but cut down models to 22 total for the two blocks. It's not as important as all the other states, but if this is going to be done, might as well.

**Comment by darthvader45** [comment]
Sounds amazing.  Keep the players posted, though.  Good to let em know what's going on.
