### ISSUE TITLE
Textures TODO

### ISSUE THREAD

**Issue by primetoxinz** [BeetoGuy/BetterWithMods#137]
I am doing really bad temporary textures but these need redone

- [x] Steel Armor Items and Player Texture
- [x] Composite Bow
- [x] Broadhead arrow and arrow item
- [x] Padding, Armor Plating and Broadhead materials
